In [11]:
from pathlib import Path
import pandas as pd
import pyreadstat

In [12]:

sav_path = Path("LAL 2025.sav")

# 1. Raw version: keeps original numeric/coded values
df_raw, meta = pyreadstat.read_sav(
    sav_path,
    apply_value_formats=False
)

# 2. Labelled version: replaces coded values with human-readable labels
df_labelled, meta_labelled = pyreadstat.read_sav(
    sav_path,
    apply_value_formats=True
)

print("Raw shape:", df_raw.shape)
print("Labelled shape:", df_labelled.shape)

df_raw.head()

Raw shape: (1664, 161)
Labelled shape: (1664, 161)

,id.case,responsemode,mergeid,q1,q1a,q1b,q1bb,q1b_dk,q1c,q2,...,dayswalk_rbr,dayscycle_rbr,dayssport_rbr,ns_sec,ns_sec_summ,dep_children,no_dep_children,receive_oow_ben,low_income_fam,workage_ndc_bens
0,00486f03-815d-4831-8d2b-a0ce1af11788,3.0,60785.0,2.0,NaN,,,NaN,NaN,2.0,...,8.0,8.0,1.0,3.0,2.0,NaN,1.0,2.0,2.0,2.0
1,0065efaf-f27a-4122-b536-abf0b1ea0913,1.0,9618.0,1.0,2.0,0,40,NaN,1.0,2.0,...,2.0,8.0,1.0,5.0,2.0,NaN,1.0,2.0,2.0,2.0
2,0067f207-733c-4fa8-8672-c1a0d121293b,2.0,8321.0,1.0,3.0,,30,NaN,1.0,2.0,...,3.0,8.0,3.0,10.0,5.0,NaN,NaN,3.0,3.0,3.0
3,00a1b94f-760c-444b-8e1f-b2fa44874874,2.0,8582.0,2.0,NaN,,,NaN,NaN,4.0,...,8.0,9.0,7.0,3.0,2.0,NaN,NaN,1.0,3.0,3.0
4,00a20603-1d79-4b04-8d58-9f896fb4f3af,1.0,7838.0,1.0,5.0,,45,NaN,2.0,2.0,...,8.0,8.0,8.0,8.0,3.0,1.0,NaN,3.0,3.0,2.0

In [13]:
df_labelled.head()

,id.case,responsemode,mergeid,q1,q1a,q1b,q1bb,q1b_dk,q1c,q2,...,dayswalk_rbr,dayscycle_rbr,dayssport_rbr,ns_sec,ns_sec_summ,dep_children,no_dep_children,receive_oow_ben,low_income_fam,workage_ndc_bens
0,00486f03-815d-4831-8d2b-a0ce1af11788,Online,60785.0,No,NaN,,,NaN,NaN,No,...,Don't know,Don't know,1 day,Intermediate occupations (NS-SEC 3),Intermediate occupations (NS-SEC 3-5),NaN,Yes,No,No,No
1,0065efaf-f27a-4122-b536-abf0b1ea0913,Face-to-face interview,9618.0,Yes,2,0,40,NaN,Yes,No,...,2 days,Don't know,1 day,Lower supervisory and technical occupations (N...,Intermediate occupations (NS-SEC 3-5),NaN,Yes,No,No,No
2,0067f207-733c-4fa8-8672-c1a0d121293b,Postal,8321.0,Yes,3,,30,NaN,Yes,No,...,3 days,Don't know,3 days,Not stated,Not stated,NaN,NaN,Not stated,Not stated,Not stated
3,00a1b94f-760c-444b-8e1f-b2fa44874874,Postal,8582.0,No,NaN,,,NaN,NaN,Prefer not to say,...,Don't know,Not stated,7 days,Intermediate occupations (NS-SEC 3),Intermediate occupations (NS-SEC 3-5),NaN,NaN,Yes,Not stated,Not stated
4,00a20603-1d79-4b04-8d58-9f896fb4f3af,Face-to-face interview,7838.0,Yes,5,,45,NaN,No,No,...,Don't know,Don't know,Don't know,Never worked and long-term unemployed (NS-SEC 8),Lower occupations (NS-SEC 6-8),Yes,NaN,Not stated,Not stated,No

In [14]:
df_q1b_dk = df_raw.dropna(subset=['q1b_dk'])

In [15]:
df_q1b_dk.head()

,id.case,responsemode,mergeid,q1,q1a,q1b,q1bb,q1b_dk,q1c,q2,...,dayswalk_rbr,dayscycle_rbr,dayssport_rbr,ns_sec,ns_sec_summ,dep_children,no_dep_children,receive_oow_ben,low_income_fam,workage_ndc_bens
7,00f2ee5d-5697-43f2-adb2-7abf50ef6c3b,2.0,1698.0,1.0,2.0,,10,2.0,1.0,2.0,...,2.0,8.0,8.0,10.0,5.0,NaN,NaN,3.0,3.0,3.0
57,08897b0e-85fb-4d40-a5dd-0cd6746a6171,2.0,4330.0,1.0,5.0,,10,1.0,2.0,1.0,...,8.0,1.0,8.0,2.0,1.0,1.0,NaN,2.0,2.0,2.0
97,0e8c91f0-b9c0-41c5-beb7-4f8c35122f52,1.0,1746.0,1.0,6.0,5,,2.0,2.0,1.0,...,8.0,6.0,8.0,6.0,3.0,1.0,NaN,1.0,1.0,2.0
98,0ed873b5-2997-43ad-84c3-1eb8f60ee0f9,3.0,60607.0,1.0,6.0,1,,1.0,1.0,2.0,...,6.0,8.0,3.0,3.0,2.0,NaN,1.0,2.0,2.0,2.0
110,103ff58d-d5ca-4efd-a262-d096bbfbaae7,3.0,1897.0,1.0,7.0,,10,1.0,3.0,2.0,...,9.0,8.0,8.0,3.0,2.0,1.0,NaN,1.0,1.0,2.0

In [16]:
df_raw.to_csv("data_raw__no_index.csv", index=False)

df_raw.to_excel("data_raw_no_index.xlsx", index=False)

In [17]:
df_labelled.to_csv("data_labelled_no_index.csv", index=False)

df_labelled.to_excel("data_labelled_no_index.xlsx", index=False)

In [18]:
variable_view = pd.DataFrame({
    "variable_name": meta.column_names,
    "variable_label": meta.column_labels,
    "type": [meta.readstat_variable_types.get(col) for col in meta.column_names],
    "format": [meta.original_variable_types.get(col) for col in meta.column_names],
    "measure": [meta.variable_measure.get(col) for col in meta.column_names],
    "missing_ranges": [meta.missing_ranges.get(col) for col in meta.column_names],
    "missing_user_values": [meta.missing_user_values.get(col) for col in meta.column_names],
    "value_label_set": [meta.variable_to_label.get(col) for col in meta.column_names]
})
variable_view

,variable_name,variable_label,type,format,measure,missing_ranges,missing_user_values,value_label_set
0,id.case,"ID,case - unique identifier - LAL 2025",string,A200,nominal,None,None,None
1,responsemode,ResponseMode,double,F1.0,nominal,None,None,labels0
2,mergeid,MergeID_Unique numeric ID,double,F8.0,scale,None,None,None
3,q1,"In the past 7 days, have you done a continuous...",double,F1.0,nominal,None,None,labels1
4,q1a,"In the past 7 days, on how many days did you d...",double,F1.0,nominal,None,None,labels2
...,...,...,...,...,...,...,...,...
156,dep_children,Any dependent children (0-15 or dependent 16-19)?,double,F1.0,nominal,None,None,labels81
157,no_dep_children,No dependent children (0-15 or dependent 16-19)?,double,F1.0,nominal,None,None,labels81
158,receive_oow_ben,Receive OOW benefits,double,F1.0,nominal,None,None,labels82
159,low_income_fam,Low Income family (dependent children 0-15 or ...,double,F1.0,nominal,None,None,labels82
160,workage_ndc_bens,"Working age adult no dependent children, on OO...",double,F1.0,nominal,None,None,labels82

In [19]:
def get_value_labels_for_variable(variable_name):
    label_set_name = meta.variable_to_label.get(variable_name)

    if label_set_name is None:
        return ""

    labels_dict = meta.value_labels.get(label_set_name, {})

    return "; ".join(
        f"{code} = {label}"
        for code, label in labels_dict.items()
    )

variable_view = pd.DataFrame({
    "variable_name": meta.column_names,
    "variable_label": meta.column_labels,
    "value_label_set": [
        meta.variable_to_label.get(col, "")
        for col in meta.column_names
    ],
    "value_labels": [
        get_value_labels_for_variable(col)
        for col in meta.column_names
    ]
})


# Save as CSV
variable_view.to_csv(
    "variable_view_with_value_labels.csv",
    index=False,
    encoding="utf-8-sig"
)

# Save as Excel
variable_view.to_excel(
    "variable_view_with_value_labels.xlsx",
    index=False
)

variable_view

,variable_name,variable_label,value_label_set,value_labels
0,id.case,"ID,case - unique identifier - LAL 2025",,
1,responsemode,ResponseMode,labels0,1.0 = Face-to-face interview; 2.0 = Postal; 3....
2,mergeid,MergeID_Unique numeric ID,,
3,q1,"In the past 7 days, have you done a continuous...",labels1,1.0 = Yes; 2.0 = No; 3.0 = Don’t know; 4.0 = P...
4,q1a,"In the past 7 days, on how many days did you d...",labels2,1.0 = 1; 2.0 = 2; 3.0 = 3; 4.0 = 4; 5.0 = 5; 6...
...,...,...,...,...
156,dep_children,Any dependent children (0-15 or dependent 16-19)?,labels81,1.0 = Yes
157,no_dep_children,No dependent children (0-15 or dependent 16-19)?,labels81,1.0 = Yes
158,receive_oow_ben,Receive OOW benefits,labels82,1.0 = Yes; 2.0 = No; 3.0 = Not stated
159,low_income_fam,Low Income family (dependent children 0-15 or ...,labels82,1.0 = Yes; 2.0 = No; 3.0 = Not stated
160,workage_ndc_bens,"Working age adult no dependent children, on OO...",labels82,1.0 = Yes; 2.0 = No; 3.0 = Not stated

In [20]:
def get_value_labels_for_variable(variable_name):
    label_set_name = meta.variable_to_label.get(variable_name)

    if label_set_name is None:
        return ""

    labels_dict = meta.value_labels.get(label_set_name, {})

    return "; ".join(
        f"{code} = {label}"
        for code, label in labels_dict.items()
    )

variable_view = pd.DataFrame({
    "variable_name": meta.column_names,
    "variable_label": meta.column_labels,
    "type": [
        meta.readstat_variable_types.get(col, "")
        for col in meta.column_names
    ],
    "format": [
        meta.original_variable_types.get(col, "")
        for col in meta.column_names
    ],
    "measure": [
        meta.variable_measure.get(col, "")
        for col in meta.column_names
    ],
    "value_label_set": [
        meta.variable_to_label.get(col, "")
        for col in meta.column_names
    ],
    "value_labels": [
        get_value_labels_for_variable(col)
        for col in meta.column_names
    ],
    "missing_ranges": [
        meta.missing_ranges.get(col, "")
        for col in meta.column_names
    ],
    "missing_user_values": [
        meta.missing_user_values.get(col, "")
        for col in meta.column_names
    ]
})

variable_view

,variable_name,variable_label,type,format,measure,value_label_set,value_labels,missing_ranges,missing_user_values
0,id.case,"ID,case - unique identifier - LAL 2025",string,A200,nominal,,,,
1,responsemode,ResponseMode,double,F1.0,nominal,labels0,1.0 = Face-to-face interview; 2.0 = Postal; 3....,,
2,mergeid,MergeID_Unique numeric ID,double,F8.0,scale,,,,
3,q1,"In the past 7 days, have you done a continuous...",double,F1.0,nominal,labels1,1.0 = Yes; 2.0 = No; 3.0 = Don’t know; 4.0 = P...,,
4,q1a,"In the past 7 days, on how many days did you d...",double,F1.0,nominal,labels2,1.0 = 1; 2.0 = 2; 3.0 = 3; 4.0 = 4; 5.0 = 5; 6...,,
...,...,...,...,...,...,...,...,...,...
156,dep_children,Any dependent children (0-15 or dependent 16-19)?,double,F1.0,nominal,labels81,1.0 = Yes,,
157,no_dep_children,No dependent children (0-15 or dependent 16-19)?,double,F1.0,nominal,labels81,1.0 = Yes,,
158,receive_oow_ben,Receive OOW benefits,double,F1.0,nominal,labels82,1.0 = Yes; 2.0 = No; 3.0 = Not stated,,
159,low_income_fam,Low Income family (dependent children 0-15 or ...,double,F1.0,nominal,labels82,1.0 = Yes; 2.0 = No; 3.0 = Not stated,,
160,workage_ndc_bens,"Working age adult no dependent children, on OO...",double,F1.0,nominal,labels82,1.0 = Yes; 2.0 = No; 3.0 = Not stated,,